Deprecate Kotest 4 and promote Kotest 5 to managed dependencies
micronaut-projects/micronaut-test pull request #609
Opened 2022-06-28 14:41 UTC by wetted

closes #604

2022-06-28 15:14 UTC, timyates approved these changes
I think this is the best we can do 👍

If only they'd changed the group or artifact id

I guess this needs to wait for Micronaut 4, as it will break anyone using Kotest and the catalog

(admittedly probably a small subset of users)

Unless we also add `kotest-assertions-core-jvm` and `kotest-runner-junit5-jvm` to the core catalog 🤔

2022-08-01 10:51 UTC, timyates commented
Wondering if we should leave these two as managed

```
managed-kotest-assertions-core-jvm
managed-kotest-runner-junit5-jvm
```

2022-08-01 10:52 UTC, timyates requested changes

2022-08-01 10:52 UTC, timyates commented on gradle/libs.versions.toml
> -managed-kotest-runner-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "managed-kotest" }
Can we leave these as managed?

2022-08-01 10:55 UTC, timyates commented on gradle/libs.versions.toml
> -managed-kotest-runner-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "managed-kotest" }
Ignore me, this would break the POM

2022-08-01 11:13 UTC, timyates commented
@wetted @sdelamo Pushed a change so we re-use existing catalog names, but now kotest5 is managed

I think it will simplify things in core, but this needs to be a major release here, and Micronaut 4.0.0

2022-08-01 11:13 UTC, timyates approved these changes

2022-08-01 14:20 UTC, wetted commented
@timyates thanks, I agree this will have to be a 4.0.x feature, for potential breaking changes to managed dependencies.

2022-08-02 04:16 UTC, merged